### ISSUE TITLE
[Question] What version is supported?

### ISSUE THREAD

**Issue by masters3d** [exercism/zig#51]
I am curious to know which version I should have? 
Or is this error a Mac thing? I am 10 minutes into zig

I know the track is not launched yet. 

<img width="755" alt="image" src="https://user-images.githubusercontent.com/6539412/112586783-9d275980-8db9-11eb-8f2e-26fc8ba7aabe.png">

**Comment by masters3d** [comment]
Currently only testing on Linux. We should add Mac and windows testing too. 

        curl -o zig.tar.xz https://ziglang.org/download/0.7.0/zig-linux-x86_64-0.7.0.tar.xz

**Comment by kotp** [comment]
I think 7.0 is reasonable. I am using  0.7.1, but we can get confirmation from @massivelivefun as well for a minimum support version.

**Comment by masters3d** [comment]
There is definitely a mac incompatibility going on https://github.com/exercism/zig/pull/54

**Comment by massivelivefun** [comment]
Okay I've been developing on Zig 0.7.1 x64 win10 and on Zig 0.7.0 x64 darwin big sur (for good reason) for my entire period contributing to this track. This development on different versions of Zig should obviously be avoided and remedied. However, with macos and some instances of linux there are large problems involving comptime. This ought to be a tool we should use given the safety checks that it provides during compile time.

However, Zig is volatile as hell to breakages right now, so we should just use Zig 0.7.0 so that we can have maximum platform support for contributors.

Please refer to these issues below:
Zig 0.7.1 x64 darwin comptime problems: ziglang/zig#7544, ziglang/zig#6971

**Comment by masters3d** [comment]
Thanks for the info. Sounds good on 0.7.0; I think the issue I am facing is with my mac set up (osx 11) because even in CI it doesn't surface https://github.com/exercism/zig/pull/56

**Comment by massivelivefun** [comment]
@masters3d Otherwise is Zig 0.7.0 x64 darwin is running fine for you? Like all of the tests are working and stuff? I wanna make sure everything is solid for everyone.
